baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Networking & DevOps'
theme = 'hugo-flex'
favicon = 'true'
faviconVersion = "1"
custom_css = ["assets/css/custom.css"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true